apiVersion: v1 
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::103621702157:user/github-ci
      username: github-ci
      groups:
        - system: masters